"""Visual perception, runtime-policy, and target-confirmation interfaces."""

from perception.base import (
    DetectorTrackerBackend,
    IdentityVerifierBackend,
    PerceptionBackend,
    SemanticVerifierBackend,
)
from perception.candidate_bank import (
    CandidateBank,
    CandidateLifecycle,
    CandidateReviewRef,
    CandidateSnapshot,
)
from perception.confirmation import (
    CandidateConfirmationCoordinator,
    CandidateConfirmationError,
    ConfirmationDecision,
    ConfirmationPolicy,
    ConfirmationResult,
)
from perception.detector_tracker import DetectorTrackerPerception
from perception.grounding import (
    CandidateResolutionUnavailable,
    CandidateResolver,
    GroundingBackend,
    GroundingBackendUnavailable,
    GroundingProposal,
    LearnedGrounder,
    OracleEvaluationCandidateResolver,
    OracleEvaluationGrounder,
    OraclePositionProvider,
    ProductionCandidateResolver,
    QwenVLGrounder,
    ResolvedCandidatePosition,
    YOLOEGrounder,
)
from perception.ideal_obstacle_perception import IdealObstaclePerception
from perception.obstacle_types import (
    CAMERA_COORDINATE_FRAME,
    CameraGeometry,
    FlightCorridor,
    IDEAL_CAMERA_OBSTACLE_SOURCE,
    MotionState,
    ObstacleAABB,
    ObstacleMotionState,
    ObstacleObservation,
    ObstacleSpec,
    VisibleObstacle,
)
from perception.oracle import OraclePerception, OraclePerceptionError
from perception.prompt_types import (
    DeterministicPromptCompiler,
    PromptBundle,
    TargetPromptAdapter,
)
from perception.qwen_vlm_verifier import (
    QwenVLMVerifier,
    VisualReviewFrame,
    VisualReviewInput,
)
from perception.reid_verifier import ReIDVerifier
from perception.runtime import (
    GuardedPerceptionBackend,
    PerceptionBoundaryError,
    PerceptionCapability,
    PerceptionRuntimeProfile,
    observation_contains_oracle_data,
    validate_observation_access,
)
from perception.runtime_visual_assessment import (
    CompletedStepSummary,
    CurrentStepSummary,
    PlanProgressSummary,
    QwenRuntimeVisualVerifierV2,
    RemainingStepSummary,
    RuntimeVisualAssessmentV2,
    RuntimeHazardAssessment,
    RuntimeSafetyState,
    RuntimeTargetAssessment,
    RuntimeVisualAction,
    RuntimeVisualDecision,
    RuntimeVisualProtocolError,
    RuntimeVisualReviewInputV2,
    TargetAssessmentStatus,
    TaskProgressAssessment,
    build_runtime_visual_assessment_v2_schema,
)
from perception.types import (
    DetectionCandidate,
    IdentityConsistencyEvidence,
    SemanticVerification,
    ShortTrackEvidence,
)
from perception.vlm_verifier import VLMVerifier
from perception.visual_review import (
    QwenVisualReview,
    ReviewDisposition,
    VisualReviewAcceptance,
    VisualReviewAction,
    VisualReviewCandidate,
    VisualReviewDecision,
    VisualReviewExpectation,
    VisualReviewGate,
    VisualReviewMode,
    VisualReviewParseErrorCode,
    VisualReviewProtocolError,
    VisualReviewStaleReason,
    build_qwen_visual_review_json_schema,
)

__all__ = [
    "CandidateBank",
    "CandidateLifecycle",
    "CandidateReviewRef",
    "CandidateSnapshot",
    "CandidateConfirmationCoordinator",
    "CandidateConfirmationError",
    "ConfirmationDecision",
    "ConfirmationPolicy",
    "ConfirmationResult",
    "DetectionCandidate",
    "DetectorTrackerBackend",
    "DetectorTrackerPerception",
    "DeterministicPromptCompiler",
    "GuardedPerceptionBackend",
    "GroundingBackend",
    "GroundingBackendUnavailable",
    "GroundingProposal",
    "IdentityConsistencyEvidence",
    "IdentityVerifierBackend",
    "IdealObstaclePerception",
    "CAMERA_COORDINATE_FRAME",
    "CameraGeometry",
    "FlightCorridor",
    "IDEAL_CAMERA_OBSTACLE_SOURCE",
    "MotionState",
    "ObstacleAABB",
    "ObstacleMotionState",
    "ObstacleObservation",
    "ObstacleSpec",
    "VisibleObstacle",
    "OraclePerception",
    "OraclePerceptionError",
    "OracleEvaluationCandidateResolver",
    "OracleEvaluationGrounder",
    "OraclePositionProvider",
    "PerceptionBoundaryError",
    "PerceptionBackend",
    "PerceptionCapability",
    "PerceptionRuntimeProfile",
    "PromptBundle",
    "ProductionCandidateResolver",
    "QwenVLMVerifier",
    "QwenVLGrounder",
    "ReIDVerifier",
    "CompletedStepSummary",
    "CurrentStepSummary",
    "PlanProgressSummary",
    "QwenRuntimeVisualVerifierV2",
    "RemainingStepSummary",
    "RuntimeVisualAssessmentV2",
    "RuntimeHazardAssessment",
    "RuntimeSafetyState",
    "RuntimeTargetAssessment",
    "RuntimeVisualAction",
    "RuntimeVisualDecision",
    "RuntimeVisualProtocolError",
    "RuntimeVisualReviewInputV2",
    "TargetAssessmentStatus",
    "TaskProgressAssessment",
    "QwenVisualReview",
    "ReviewDisposition",
    "SemanticVerification",
    "SemanticVerifierBackend",
    "ShortTrackEvidence",
    "TargetPromptAdapter",
    "CandidateResolutionUnavailable",
    "CandidateResolver",
    "LearnedGrounder",
    "ResolvedCandidatePosition",
    "VLMVerifier",
    "VisualReviewAcceptance",
    "VisualReviewAction",
    "VisualReviewCandidate",
    "VisualReviewDecision",
    "VisualReviewExpectation",
    "VisualReviewFrame",
    "VisualReviewGate",
    "VisualReviewInput",
    "VisualReviewMode",
    "VisualReviewParseErrorCode",
    "VisualReviewProtocolError",
    "VisualReviewStaleReason",
    "YOLOEGrounder",
    "build_qwen_visual_review_json_schema",
    "build_runtime_visual_assessment_v2_schema",
    "observation_contains_oracle_data",
    "validate_observation_access",
]
